import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { WorldsGeneratedModule, WorldsGeneratedSharedModule } from './generated/module';
import { WorldsValidator, registerValidationChecks } from './worlds-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type WorldsAddedServices = {
    validation: {
        WorldsValidator: WorldsValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type WorldsServices = LangiumServices & WorldsAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const WorldsModule: Module<WorldsServices, PartialLangiumServices & WorldsAddedServices> = {
    validation: {
        WorldsValidator: () => new WorldsValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createWorldsServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Worlds: WorldsServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        WorldsGeneratedSharedModule
    );
    const Worlds = inject(
        createDefaultModule({ shared }),
        WorldsGeneratedModule,
        WorldsModule
    );
    shared.ServiceRegistry.register(Worlds);
    registerValidationChecks(Worlds);
    return { shared, Worlds };
}
